/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import controller.C_Register;
import errorhandler.H_Error;


/**
 *
 * @author Raynald Krisnawan
 */
public class UI_Register extends javax.swing.JFrame {
    C_Register cRegister;

    /**
     * Creates new form UI_Register
     */
    public UI_Register() {
        initComponents();
        this.setLocationRelativeTo(null);
        cRegister = new C_Register(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        I_username = new javax.swing.JTextField();
        B_Back = new javax.swing.JButton();
        I_password = new javax.swing.JPasswordField();
        B_Confirm = new javax.swing.JButton();
        C_ShowPass = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        I_Nama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        I_Alamat = new javax.swing.JTextField();
        I_Telepon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        I_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_usernameActionPerformed(evt);
            }
        });

        B_Back.setText("Back");
        B_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BackActionPerformed(evt);
            }
        });

        I_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_passwordActionPerformed(evt);
            }
        });

        B_Confirm.setText("Confirm");
        B_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ConfirmActionPerformed(evt);
            }
        });

        C_ShowPass.setText("Show Password");
        C_ShowPass.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_ShowPassStateChanged(evt);
            }
        });

        jLabel5.setText("Nama");

        I_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_NamaActionPerformed(evt);
            }
        });

        jLabel6.setText("Alamat");

        I_Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_AlamatActionPerformed(evt);
            }
        });

        I_Telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_TeleponActionPerformed(evt);
            }
        });
        I_Telepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                I_TeleponKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                I_TeleponKeyTyped(evt);
            }
        });

        jLabel7.setText("Telepon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(I_Telepon))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(I_Alamat))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(I_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(C_ShowPass)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(I_username)
                                .addComponent(I_password))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(B_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(I_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(I_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_ShowPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I_Telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Back)
                    .addComponent(B_Confirm))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void I_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_usernameActionPerformed

    private void B_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BackActionPerformed
        UI_Login new_UI = new UI_Login();
        new_UI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_B_BackActionPerformed

    private void I_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_passwordActionPerformed

    private void C_ShowPassStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_ShowPassStateChanged
        // TODO add your handling code here:
        if(C_ShowPass.isSelected()){
            I_password.setEchoChar((char)0);
        }
        else{
            I_password.setEchoChar('*');
        }
    }//GEN-LAST:event_C_ShowPassStateChanged

    private void I_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_NamaActionPerformed

    private void I_AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_AlamatActionPerformed

    private void I_TeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_TeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_TeleponActionPerformed

    private void B_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ConfirmActionPerformed
        // TODO add your handling code here:
        if(!cRegister.Null_Checker()){
            cRegister.inputUser();
            if(cRegister.Check_Data()){
                JOptionPane.showMessageDialog(null, "Registrasi Berhasil", "Registration Success", JOptionPane.INFORMATION_MESSAGE);
                UI_Login ui = new UI_Login();
                ui.setVisible(true);
                this.dispose();
            }
            else{
                H_Error.failure_registration();
            }
        }
    }//GEN-LAST:event_B_ConfirmActionPerformed

    private void I_TeleponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_I_TeleponKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9'  || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
               I_Telepon.setEditable(true);
        } 
        else {
               I_Telepon.setEditable(false);
               H_Error.wrong_telepon();
        }
    }//GEN-LAST:event_I_TeleponKeyPressed

    private void I_TeleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_I_TeleponKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_I_TeleponKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Register().setVisible(true);
            }
        });
    }

    public JButton getB_Back() {
        return B_Back;
    }

    public void setB_Back(JButton B_Back) {
        this.B_Back = B_Back;
    }

    public JButton getB_Confirm() {
        return B_Confirm;
    }

    public void setB_Confirm(JButton B_Confirm) {
        this.B_Confirm = B_Confirm;
    }

    public JCheckBox getC_ShowPass() {
        return C_ShowPass;
    }

    public void setC_ShowPass(JCheckBox C_ShowPass) {
        this.C_ShowPass = C_ShowPass;
    }

    public JTextField getI_Alamat() {
        return I_Alamat;
    }

    public void setI_Alamat(JTextField I_Alamat) {
        this.I_Alamat = I_Alamat;
    }

    public JTextField getI_Nama() {
        return I_Nama;
    }

    public void setI_Nama(JTextField I_Nama) {
        this.I_Nama = I_Nama;
    }

    public JTextField getI_Telepon() {
        return I_Telepon;
    }

    public void setI_Telepon(JTextField I_Telepon) {
        this.I_Telepon = I_Telepon;
    }

    public JPasswordField getI_password() {
        return I_password;
    }

    public void setI_password(JPasswordField I_password) {
        this.I_password = I_password;
    }

    public JTextField getI_username() {
        return I_username;
    }

    public void setI_username(JTextField I_username) {
        this.I_username = I_username;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Back;
    private javax.swing.JButton B_Confirm;
    private javax.swing.JCheckBox C_ShowPass;
    private javax.swing.JTextField I_Alamat;
    private javax.swing.JTextField I_Nama;
    private javax.swing.JTextField I_Telepon;
    private javax.swing.JPasswordField I_password;
    private javax.swing.JTextField I_username;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
